config/routes.rb
Rails.application.routes.draw do
root 'posts#index'
resources :posts

end

app/models/post.rb
class Post < ActiveRecord::Base
	validates :image, presence: true

	has_attached_file :image, styles: { medium: "640px640px>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end


def create 
	@post = Post.create(params[:post])
	redirect_to posts_path
end


private

def post_params
	params.require(:post).permit(:image, :caption)
end

def index
	@posts = Post.all
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def new  
  @post = Post.new
end

def create
	@post = Post.create(post_params)
	redirect_to posts_path
end

def index 
	@posts = Post.all
end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
end

def index
	@posts = Post.all.order(created_at: :desc)
end

def new 
	@post = Post.new
end

def destroy
	@post = Post.find(params[:id])
	@post.destroy
	redirect_to posts_path
end


def show
	@post = Post.find(params[:id])
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Chestogram</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

<nav class="navbar navbar-default">
  <div class="navbar-container">
    <div class="navbar-header">
      <button class="navbar-toggle collapsed" data-target="#bs-navbar-collapse-1" data-toggle="collapse" type="button">
        <span class="sr-only">Toggle Navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="navbar-brand">
        <%= link_to "Chestogram", root_path %>
      </div>
    </div>
    <div class="collapse navbar-collapse" id="bs-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to "New Post", new_post_path %>
        </li>
        <li>
          <%= link_to "Login", '#' %>
        </li>
        <li>
          <%= link_to "Register", '#' %>
        </li>
      </ul>
    </div>
  </div>
</nav>


</head>
<body>





<%= yield %>

</body>




</html>

app/views/posts/index.html.erb
<div class="posts-wrapper row">
  <% @posts.each do |post| %>
    <div class="post">
      <div class="post-head">
        <div class="name">
          Derek
        </div>
      </div>
      <div class="image center-block">
        <%= link_to (image_tag post.image.url(:medium), class:'img-responsive'), post_path(post) %>
      </div>
      <p class="caption">
        <%= post.caption %>
      </p>
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<html>

<head>
	
	
</head>

<div class="form-wrapper">
  <%= simple_form_for @post, html: { class: 'form-horizontal', multipart: true } do |f| %>
    <div class="form-group">
      <%= f.input :image %>
    </div>
    <div class="form-group text-center">
      <%= f.input :caption %>
    </div>
    <div class="form-group text-center">
      <%= f.button :submit, class: 'btn-success' %>
    </div>
  <% end %>

</html>

app/views/posts/show.html.erb
<html>

<div class="posts-wrapper row">
  <div class="post">
    <div class="post-head">
      <div class="name">
        Ben Walker
      </div>
    </div>
    <div class="image center-block">
      <%= image_tag @post.image.url(:medium) %>
    </div>
    <p class="caption">
      <%= @post.caption %>
    </p>
    <div class="text-center">
      <%= link_to "Cancel", posts_path %>
    </div>
  </div>
</div>

</html>